LiquidTag:
  enabled: false
TemplateLength:
  enabled: false
AssetPreload:
  enabled: false
RemoteAsset:
  enabled: false
ImgLazyLoading:
  enabled: false

SchemaJsonFormat:
  enabled: true

ValidSchema:
  enabled: false
