extends: theme-check:recommended

ValidJson:
  enabled: true
ValidSchema:
  enabled: true

LiquidTag:
  enabled: false

TemplateLength:
  enabled: true
  severity: suggestion
  max_length: 600

ignore:
  - backups/**
