# Skip style-only complaints if you want a clean output
ignored_checks:
  - SchemaJsonFormat

# Don’t scan temp reports (and other junk)
exclude_patterns:
  - tmp/**
  - theme-check-report.json
  - node_modules/**
