name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Affiche les noms des secrets
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
          echo "SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }}"
          echo "SHOPIFY_ADMIN_TOKEN=${{ secrets.SHOPIFY_ADMIN_TOKEN }}"
          echo "SHOPIFY_STORE=${{ secrets.SHOPIFY_STORE }}"
          # Ajoute d'autres clés ici si besoin
