name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Affiche les noms des secrets
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
          echo "SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }}"
          echo "SHOPIFY_ADMIN_TOKEN=${{ secrets.SHOPIFY_ADMIN_TOKEN }}"
          echo "SHOPIFY_STORE=${{ secrets.SHOPIFY_STORE }}"

      - name: Deep scan and fail if missing
        run: |
          echo "Scanning all required secrets..."
          missing=0
          for key in GOOGLE_API_KEY SHOPIFY_API_KEY SHOPIFY_ADMIN_TOKEN SHOPIFY_STORE; do
          value="${{ secrets["$key"] }}"
            if [ -z "$value" ]; then
              echo "::error::Secret $key is missing or empty!"
              missing=1
            else
              echo "$key is set."
            fi
          done
          if [ $missing -eq 1 ]; then
              echo "::error::One or more secrets are missing. Failing workflow."
              exit 1
            fi
