name: test-secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to test"
        required: false
        default: "dev"
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: echo "env=${{ github.event.inputs.env != '' && github.event.inputs.env || 'dev' }}"
