name: test-secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment to test
        required: false
        default: dev
  push:
    branches: [ main ]  # optional

permissions:
  contents: read

concurrency:
  group: test-secrets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.env != '' && github.event.inputs.env || 'dev' }}
    steps:
      - name: Show input
        run: echo "env=${ENVIRONMENT}"

      - name: Check required secrets exist
        run: |
          missing=0
          for key in GOOGLE_API_KEY SHOPIFY_API_KEY SHOPIFY_ADMIN_TOKEN SHOPIFY_STORE; do
            val="${{ secrets[key] }}"
            if [ -z "$val" ]; then
              echo "::error::Secret $key is missing"
              missing=1
            else
              echo "$key is set."
            fi
          done
          exit $missing
