name: CI Shopify Theme

on:
  push:
    branches: [ main, DEV ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  theme-check:
    name: 🧹 Lint & Theme Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install theme-check
        run: gem install theme-check

      - name: Run theme-check
        run: theme-check

  build:
    name: 🧱 Build & Sanity check
    runs-on: ubuntu-latest
    needs: theme-check

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check required Shopify theme files
        run: |
          test -f layout/theme.liquid || (echo "❌ layout/theme.liquid missing" && exit 1)
          test -f config/settings_schema.json || (echo "❌ config/settings_schema.json missing" && exit 1)
          echo "✅ All required files are present."
