name: Theme CI (structure + sanity + JSON)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  theme-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure jq
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Sanity | theme structure at repo root
        shell: bash
        run: |
          set -euo pipefail
          for p in layout/theme.liquid config/settings_schema.json; do
            if [[ ! -f "$p" ]]; then
              echo "::error file=$p::missing required file $p"
              exit 1
            fi
          done
          for d in assets sections snippets templates locales; do
            if [[ ! -d "$d" ]]; then
              echo "::error file=$d::missing required folder $d"
              exit 1
            fi
          done
          echo "Theme structure OK ✅"

      - name: Validate JSON files (locales)
        shell: bash
        run: |
          set -euo pipefail
          find locales -type f -name '*.json' -print0 |
          while IFS= read -r -d '' f; do
            echo "Checking $f"
            jq empty "$f"
          done
          echo "✅ All locale JSON files valid"

      - name: Add gem bin path to PATH for later steps
        shell: bash
        run: |
          GEM_BIN="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
          echo "$GEM_BIN" >> "$GITHUB_PATH"

      - name: Run theme-check (Ruby CLI)
        shell: bash
        run: |
          set -euo pipefail
          gem install --user-install theme-check
          echo "theme-check version:"
          theme-check --version
          echo "Running theme-check..."
          theme-check .
