---
name: Theme CI (structure + sanity + JSON)

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  theme-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure toolchain (jq + node/npm)
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq nodejs npm
          node -v
          npm -v

      - name: Sanity | theme structure at repo root
        shell: bash
        run: |
          set -euo pipefail
          for p in layout/theme.liquid config/settings_schema.json; do
            if [[ ! -f "$p" ]]; then
              echo "::error file=$p::missing required file $p"
              exit 1
            fi
          done
          for d in assets sections snippets templates locales; do
            if [[ ! -d "$d" ]]; then
              echo "::error file=$d::missing required folder $d"
              exit 1
            fi
          done
          echo "Theme structure OK ✅"

      - name: Validate JSON files (locales)
        shell: bash
        run: |
          set -euo pipefail
          find locales -type f -name '*.json' -print0 \
          | while IFS= read -r -d '' f; do
              echo "Checking $f"
              jq empty "$f"
            done
          echo "✅ All locale JSON files valid"

      - name: Run theme-check (skip when ACT=true)
        if: ${{ env.ACT != 'true' }}
        uses: shopify/theme-check-action@v2
        with:
          flags: --fail-level error
          # config: .theme-check.yml

      - name: Validate Liquid syntax
        shell: bash
        run: |
          set -euo pipefail
          npm install -g @shopify/liquid-linter
          liquid-linter \
            "sections/**/*.liquid" \
            "snippets/**/*.liquid" \
            "layout/**/*.liquid" \
            "templates/**/*.liquid"

      - name: Check asset file sizes
        shell: bash
        run: |
          set -euo pipefail
          large_files=$(find assets -type f -size +500k || true)
          if [[ -n "$large_files" ]]; then
            echo "::error::Found asset files > 500KB:"
            echo "$large_files"
            exit 1
          fi
          echo "✅ All asset files are under 500KB"

      - name: Validate section schemas (presence only)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for file in sections/*.liquid; do
            if ! grep -q '{% schema %}' "$file"; then
              echo "::error file=$file::Missing schema tag"
              exit 1
            fi
          done
          echo "✅ All section files contain schema tags"
