name: Theme CI (structure + sanity + JSON)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  theme-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity: theme structure at repo root
        run: |
          set -e
          for p in layout/theme.liquid config/settings_schema.json; do
            [ -f "$p" ] || { echo "::error file=$p::missing required file $p"; exit 1; }
          done
          for d in assets sections snippets templates locales; do
            [ -d "$d" ] || { echo "::error file=$d::missing required folder $d"; exit 1; }
          done
          echo "Theme structure OK ✅"

      - name: Validate JSON files
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          find locales -name "*.json" -type f | while read f; do
            echo "Checking $f"
            jq empty "$f" 2>/dev/null || { echo "::error file=$f::Invalid JSON"; exit 1; }
          done
          echo "✅ All locale JSON files valid"

      - name: Run theme-check
        uses: shopify/theme-check-action@v2
        with:
          fail_level: error
