---
name: Theme CI (structure + sanity + JSON)

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  theme-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Installe Node proprement (sans apt)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure jq
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Sanity | theme structure at repo root
        shell: bash
        run: |
          set -euo pipefail
          for p in layout/theme.liquid config/settings_schema.json; do
            if [[ ! -f "$p" ]]; then
              echo "::error file=$p::missing required file $p"
              exit 1
            fi
          done
          for d in assets sections snippets templates locales; do
            if [[ ! -d "$d" ]]; then
              echo "::error file=$d::missing required folder $d"
              exit 1
            fi
          done
          echo "Theme structure OK ✅"

      - name: Validate JSON files (locales)
        shell: bash
        run: |
          set -euo pipefail
          find locales -type f -name '*.json' -print0 |
          while IFS= read -r -d '' f; do
            echo "Checking $f"
            jq empty "$f"
          done
          echo "✅ All locale JSON files valid"

      - name: Add gem bin path to PATH for later steps
        run: echo "$(ruby -r rubygems -e 'puts Gem.user_dir')/bin" >> "$GITHUB_PATH"

      - name: Run theme-check (Ruby CLI)
        shell: bash
        run: |
          set -euo pipefail
          gem install theme-check -N --user-install
          export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          GEM_BIN="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
          echo "Using GEM_BIN=$GEM_BIN"
          hash -r
          which theme-check || true
          theme-check --version
          theme-check --fail-level error

      - name: Prettier check (Liquid/JSON)
        shell: bash
        run: |
          npm install -g prettier @shopify/prettier-plugin-liquid
          prettier -c \
            "sections/**/*.liquid" \
            "snippets/**/*.liquid" \
            "layout/**/*.liquid" \
            "templates/**/*.liquid" \
            "locales/**/*.json" \
            "config/**/*.json"

      - name: Check asset file sizes
        shell: bash
        run: |
          large_files=$(find assets -type f -size +500k || true)
          if [[ -n "$large_files" ]]; then
            echo "::error::Found asset files > 500KB:"
            echo "$large_files"
            exit 1
          fi
          echo "✅ All asset files are under 500KB"

      - name: Validate section schemas (presence only)
        shell: bash
        run: |
          shopt -s nullglob
          for file in sections/*.liquid; do
            if ! grep -q '{% schema %}' "$file"; then
              echo "::error file=$file::Missing schema tag"
              exit 1
            fi
          done
          echo "✅ All section files contain schema tags"
